apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
  annotations:
    kluctl.io/wait-readiness: "true"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0