apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- workflow-template-aks.yaml
- workflow-template-resource-group.yaml
- workflow-template-subnet.yaml
- workflow-template-vnet.yaml
