apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-tpl-provider-config-kubernetes
  namespace: argo
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: aks-name
    retryStrategy:
      limit: "100"
      retryPolicy: "Always"
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "2m"
    resource:
      action: apply
      manifest: |
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        metadata:
          name: kubernetes-provider
        spec:
          credentials:
            secretRef:
              key: attribute.kube_admin_config_raw
              name: {{inputs.parameters.aks-name}}-connection
              namespace: crossplane-system
            source: Secret


